export default {
  // root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  //auth
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  INPUT_OTP: 'INPUT_OTP',
  INPUT_INFORMATION: 'INPUT_INFORMATION',
  THE_QUESTION_REGISTER: 'THE_QUESTION_REGISTER',
  UPDATE_INFORMATION: 'UPDATE_INFORMATION',
  UPDATE_CITIZEN_ID: 'UPDATE_CITIZEN_ID',
  COMPLETE_REGISTER: 'COMPLETE_REGISTER',
  //bottom
  HOME_SCREEN: 'HOME_SCREEN',
  INCOME_SCREEN: 'INCOME_SCREEN',
  HISTORY_SCREEN: 'HISTORY_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  //common
  TESTS: 'TESTS',
  NOT_YET_TEST: 'NOT_YET_TEST',
  COMPLETE_TEST: 'COMPLETE_TEST',
  FAIL_TEST: 'FAIL_TEST',
  CHOOSE_SERVICE: 'CHOOSE_SERVICE',
};
