export default {
  // root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  //auth
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  INPUT_OTP: 'INPUT_OTP',
  INPUT_INFORMATION: 'INPUT_INFORMATION',
  THE_QUESTION_REGISTER: 'THE_QUESTION_REGISTER',
  UPDATE_INFORMATION: 'UPDATE_INFORMATION',
  UPDATE_CITIZEN_ID: 'UPDATE_CITIZEN_ID',
  COMPLETE_REGISTER: 'COMPLETE_REGISTER',
  //bottom
  HOME_SCREEN: 'HOME_SCREEN',
  INCOME_SCREEN: 'INCOME_SCREEN',
  HISTORY_SCREEN: 'HISTORY_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  //top
  NEW_JOB: 'NEW_JOB',
  RECEIVE_JOB: 'RECEIVE_JOB',
  DOING_JOB: 'DOING_JOB',
  COMPLETE_JOB: 'COMPLETE_JOB',
  CANCEL_JOB: 'CANCEL_JOB',
  //common
  TESTS: 'TESTS',
  NOT_YET_TEST: 'NOT_YET_TEST',
  COMPLETE_TEST: 'COMPLETE_TEST',
  FAIL_TEST: 'FAIL_TEST',
  CHOOSE_SERVICE: 'CHOOSE_SERVICE',
  DETAIL_INCOME: 'DETAIL_INCOME',
  DETAIL_JOB_NEW: 'DETAIL_JOB_NEW',
  DETAIL_RECEIVE_JOB: 'DETAIL_RECEIVE_JOB',
  DETAIL_DOING_JOB: 'DETAIL_DOING_JOB',
  DETAIL_COMPLETE_JOB: 'DETAIL_COMPLETE_JOB',
  DETAIL_CANCEL_JOB: 'DETAIL_CANCEL_JOB',
};
